plotly/graphing-library-docs

.circleci/config.yml
The purpose of this PR is to transition from using the `documentation` repo to using this one to deploy changes to the `gh-pages` branch of the documentation repo.
=> change target branch in documentation repo to gh-pages for deploy

_posts/plotly_js/basic/bar/2015-08-07-barchart-direct-labels.html, _posts/plotly_js/basic/bar/2018-02-27-bar-base.html
Noticed that this example did not work properly on CodePen.  Did
a hex dump and noticed that string was terminated by UTF-encoded
right single quotation mark (U+2019) rather than a standard
apostrophe (U+0027).
=> fix JavaScript syntax error caused by U+2019 instead of apostrophe

all_static/javascripts/algolia/algolia.js
The purpose of this PR is to make sure hyperlinks to the reference pages in the search modal do not result in a 404 page. 
This is happening because the `permalink` attribute does not include the language. Therefore it is necessary to insert the language into the permalink as the result is returned from algolia.
=> make sure links to reference page in search modal don't 404

_includes/layouts/head.html
The purpose of this PR is to add a build timestamp as an html comment to the `head` element of every page. 
This will make it easier to keep track of which version of the site is in production.
=> add build timestamp

_includes/layouts/_footer-main.html
closes https://github.com/plotly/graphing-library-docs/issues/26
It turns out that `moment.js` uses an anonymous define, which `require.js` does not like. Since there are no references to `moment()` in the repo, should be safe to delete the script. 
Prod:
This branch:
=> remove moment.js

all_static/css/main.css
The purpose of this PR is to make sure that text does not overflow the window on mobile.
=> make sure text does not overflow window

all_static/css/main.css
addresses https://github.com/plotly/marketing-website/issues/313
For Windows users, the current `font-size` of `1rem` causes display issues as different letters render at different heights. 
Removing the style which introduces rem units forces the sidebar element to default to using the `body` font-size of `14px` across all languages. 
This was tested by running the `bundle exec rake serve` command and using the Chrome inspector to make sure that the font-size of the sidebar anchors across all languages are 14px.  
Screenshots:
=> make sure sidebar font is 14px across languages

_includes/layouts/_header-main.html
The purpose of this PR is to add a github stars button to pages beyond just the index page, on a per-language basis. The github button disappears at the same breakpoint as the `demo dash` button.
Screenshots:
=> add github stars to header

_posts/python/chart-studio/2019-07-03-embedding-charts.html
closes https://github.com/plotly/graphing-library-docs/issues/57
=> fix dead link

_includes/layouts/head.html
closes https://github.com/plotly/graphing-library-docs/issues/70 
The purpose of this PR is to make sure each page has a `<link rel="canonical"/>` tag for SEO purposes.
=> add canonical link tag

_includes/layouts/grid-item.html, _includes/posts/mainlang_documentation_eg.html, _posts/ggplot2/2016-12-16-ggplot2-index.md, _posts/julia/2015-04-05-julia-index.html, _posts/matlab/2015-04-05-matlab-index.html, _posts/nodejs/2015-04-05-node_js-index.html, _posts/plotly_js/2015-04-05-plotly_js-index.html, _posts/plotly_js/fundamentals/eula/2015-07-11-eula.html, _posts/plotly_js/legacy/polar/2015-04-09-polar_plotly_js_index.html, _posts/python/2019-07-03-chart-events-index.html, _posts/python/2019-07-03-index.html, _posts/r/2015-07-30-r-index.md, _posts/scala/2016-04-13-scala-index.html
The purpose of this PR is to refactor how examples are displayed on the language index pages for Python, R and JS. A new layout include, `mainlang_documentation.html`, is used just in those three languages to achieve the refactor. 
As a result of this PR, examples will show up on the language index page for Python, R, and JS if they have `order` less than 6. The `page_type: example_index` front-matter is no longer used to determine whether an example should be on the language index page for those 3 languages.
=> refactor language index and subindex grid layout

check-or-enforce-order.py
The `check-or-enforce-order.py` script no longer has to deal with posts in the plotly.py or plotly.r repo not having `order: 5`.
=> get rid of unneeded logic in order script

_data/cache_bust_css.yml, all_static/css/main.css
The purpose of this PR is to make sure that the homepage hero and the navbar do not overlap due to the BLM banner at mobile screen widths.
=> Mobile css fixup

all_static/css/main.css
Before: 
After:
closes https://github.com/plotly/graphing-library-docs/issues/91
=> Fix CSS on /python/renderers

_posts/plotly_js/fundamentals/texttemplate/2019-10-21-add_text_template.html, _posts/plotly_js/fundamentals/texttemplate/2019-10-21-customize_text_template.html
Fix links for both sections at https://plotly.com/javascript/texttemplate/ to point to JS
=> [plotly.js] Fundamentals -> Text templates: Fix links to point to JS

_posts/r/2021-08-17-ai-index.md
This PR adds the index page for the AI/ML page on the R graphing library docs.
=> Adding R AI index page

.circleci/config.yml
Now that the original page no longer exists, this PR updates the following snapshot link in the CI file from:
`cp --parents 'ggplot2/geom_abline/index.html' '../snapshots'`
to:
`cp --parents 'ggplot2/2D-Histogram/index.html' '../snapshots'`
=> Change ggplot2 snapshot page

Gemfile, _config.yml, _config_dev.yml, _layouts/base.html
This PR adds the jekyll-seo plugin to handle per-page SEO improvements, and default meta-tag behaviour. The seo flag is added above the header in the main site layout.
=> Adding jekyll-seo plugin

Gemfile, _config.yml, _config_dev.yml, _includes/layouts/seo.html, _layouts/base.html
Closes #171 
This PR also removes the redundant meta tags from `jekyll-seo` in place of the interpolated language/page-specific ones.
=> Meta tag fixes

_posts/plotly_js/financial/indicator1/2019-07-29-above-other-traces.html
The `ticker` option is not valid for indicator charts. In fact, I did a full search over the https://github.com/plotly/plotly.js repo and didn't find any mention for that option anywhere (except for being present in the automated test for this example/post)
Related PR: https://github.com/plotly/plotly.js/pull/6224
EDIT: seems like `vmax` is also invalid for indicator charts...
=> indicator trace: remove the invalid "ticker" option

_includes/layouts/head.html
Updates the favicon URL to point to the one used on the `plotly.com` marketing website.
=> Updating favicon url

_includes/layouts/_header-main.html
The forum links currently throw an "Oops! That page doesn’t exist or is private." error.
This updates the links to the following:
**Python:** https://community.plotly.com/c/plotly-python/5
**JS :** https://community.plotly.com/c/plotly-js/6
**Other languages:** https://community.plotly.com/c/plotly-r-matlab-julia-net/29
@Coding-with-Adam
=> Fix forum links

_includes/layouts/breadcrumb.html
The "Suggest an edit" links don't go to a page on Github.
Looks like we are not constructing the link correctly. Just wanted to confirm @nicolaskruchten, it is those .md files that the the eventual HTML files for the Julia pages are built off of?
=> Fix Julia "suggest an edit" links

_posts/plotly_js/basic/bar/2015-07-08-colored-and-styled-bar-chart.html, _posts/plotly_js/basic/dot/2015-08-11-categorical-dot-plot.html, _posts/plotly_js/fundamentals/axes/2015-04-09-axes-labels.html, _posts/plotly_js/fundamentals/sizing/2018-10-08-automargin.html, _posts/plotly_js/maps/scatter-plot-on-maps/2015-07-11-canadian-cities.html, _posts/plotly_js/maps/scatter-plot-on-maps/2015-08-15-north-america-percipitation-map.html, _posts/plotly_js/maps/scattermapbox/2017-08-01-scattermapbox_colorscale.html, _posts/plotly_js/scientific/carpet-contour/2017-05-16-mulitple_contourcarpet.html, _posts/plotly_js/scientific/contour/2015-08-12-color-bar-title.html, _posts/plotly_js/scientific/ternary-plots/2016-04-13-basic-ternary-plot.html, _posts/plotly_js/statistical/error-bar/2015-04-09-error-bar-style.html, _posts/plotly_js/statistical/splom/2018-05-23-diabetes.html, _posts/plotly_js/subplot/multiple-axes/2015-04-09-multiple-axes-double.html, _posts/plotly_js/subplot/multiple-axes/2015-04-09-multiple-axes-multiple.html
https://github.com/plotly/plotly.js/pull/7216
and
https://github.com/plotly/plotly.js/pull/7212
=> Remove deprecated attributes from docs

_posts/plotly_js/statistical/continuous-error-bars/2016-02-15-filled-lines.html
Match trace name for the "Ideal" error bars to the "Ideal" trace
=> Fix Typo On Continuous Error Bars

_posts/plotly_js/basic/dot/2015-08-11-categorical-dot-plot.html, _posts/plotly_js/basic/line-plots/2015-08-07-labelling-with-annotations.html, _posts/plotly_js/fundamentals/axes/2015-04-09-axes-ticks.html, _posts/plotly_js/fundamentals/colorscales/2015-08-10-discretized-heatmap-colorscale.html, _posts/plotly_js/fundamentals/images/2016-06-21-logo.html, _posts/plotly_js/fundamentals/shapes/2015-08-10-venn-diagram-with-circle-shapes.html
Without that, some example plots cannot be rendered properly (e. g. <https://plotly.com/javascript/dot-plots/#categorical-dot-plot>).
Looks like this problem was introduced in pull request <https://github.com/plotly/graphing-library-docs/pull/328>.
=> Fix tickmode JavaScript syntax in examples

_includes/layouts/head.html
Goes with #4992 to remove use of requirejs.
=> Remove use of requirejs in template

_posts/plotly_js/basic/sankey/2019-11-20-nodes-position.html
Without that adjustment, one of the examples does not render the title. See <https://plotly.com/javascript/sankey-diagram/#define-node-position>. The possibility to just use `title` instead of `title.text` to set a plot's title was removed in Plotly.js 3.0.0.
=> Fix Sankey example to use `title.text` instead of `title`

_posts/plotly_js/fundamentals/latex/2015-04-09-latex.html
Without the escapes, JavaScript interprets the backslashes as starting escape sequences, and the LaTeX fails to render properly, as can be seen by looking at [the docs](https://plotly.com/javascript/LaTeX/).  For example, '\sqrt' shows up as *sqrt* in the x-axis; it should be an actual square-root sign.
We just want backslashes passed through to LaTeX, so this PR escapes the backslashes.  It renders properly, as can be verified by pasting into [codepen](https://codepen.io/moble/pen/LEPXeeM).
=> Escape backslashes so that they make it to MathJax

_posts/plotly_js/fundamentals/config-options/2020-01-24-add-button-to-modebar.html
Fix typo in 
https://plotly.com/javascript/configuration-options/#add-buttons-to-modebar
The `modebardisplay` should be put in `config` instead of `layout`, but the name is actually wrong. It should be `displayModeBar`.
And since this example shows how to add a custom button, it is pointless to disable it.
I set it to `true` so the modebar is always visible, but it is optional.
=> fix typo in `Add Buttons to ModeBar` example code

_includes/layouts/_header-main.html, _includes/layouts/side-bar.html
Bring users back to /python when on python pages
=> Fix logo link
