plotly/graphing-library-docs

_includes/layouts/_header-main.html
all_static/css/main.css

add covid banner

---

all_static/css/main.css

move close button down so it aligns with search icon

---

_posts/2015-07-26-index.html

remove dash hyperlink from index.html

---

_includes/layouts/_header-main.html

per https://github.com/plotly/dash-docs/pull/832#issuecomment-607002128

remove covid banner

---

_includes/layouts/_footer-main.html
all_static/javascripts/algolia/algolia.js

closes https://github.com/plotly/documentation/issues/1681

make sure search modal closes on click

---

all_static/css/main.css

Fix ui bug

---

.circleci/config.yml

closes https://github.com/plotly/graphing-library-docs/issues/12

re-snapshot ggplot2/getting-started

---

all_static/css/main.css

closes https://github.com/plotly/documentation/issues/1684

change font from campaign to open sans

---

_data/cache_bust_css.yml
all_static/css/main.css

make sure modal is not hidden due to campaign-zero banner

---

_posts/plotly_js/fundamentals/marker-style/2018-03-15-marker-opacity.html
_posts/plotly_js/subplot/subplots/2015-08-10-multiple-custom-sized-subplots.html
_posts/python-v3/advanced/marker-style/2015-06-30-marker-style.html
_posts/python-v3/advanced/marker-style/marker-style.ipynb
_posts/python-v3/fundamentals/mixed/mixed.ipynb
_posts/python-v3/fundamentals/multiple-axes/multiple-axes.ipynb

Corrected spelling mistake "mulitple" to "multiple"

fix typo in documentation

---

_posts/python/2019-07-03-maps-index.html

I've tried adding it to maps. I haven't tested it visually yet, but I tried opening the HTML file manually and it seems fine

[WIP] Add Dash snippets to index pages

---

_includes/layouts/head.html

Updates conditional to match R language for ggplot2 pages.

Update head.html for ggplot2

---

_includes/layouts/seo.html

Adds some additional conditions for SEO to handle pages with fewer than 8 graph examples.
@danton267

Added SEO counter changes

---

_includes/layouts/webinar_plug.html

Changes the sidebar ad to the upcoming webinar and adds alt text.
First PR in this repo! I didn't test this but if I end up making more PRs in here I'll try to get it set up locally. :) 
Not sure who usually approves things in this repo so I picked your name based on activity @HammadTheOne!
CC @jingningzhang1

Change ad to July 2022 webinar

---

_includes/layouts/webinar_plug.html

Switch ad to August 2022 webinar

---

_includes/layouts/webinar_plug.html

The webinar is already over so hoping for a quick merge!

Change sidebar ad back to Dash Club

---

_includes/layouts/webinar_plug.html

For merging around 2 pm Eastern today.

Swap sidebar ad back to Dash Club

---

_includes/layouts/webinar_plug.html

Changes the sidebar ad to the upcoming Dash AG Grid webinar.
@HammadTheOne I'll put @LiamConnors as reviewer on these unless he's away! So you're mostly relieved of this very exciting duty.

Update sidebar ad to Jan 2023 webinar

---

_posts/plotly_js/basic/line_and_scatter/2022-12-13-group-scatter-setting-gap.html
_posts/plotly_js/basic/line_and_scatter/2022-12-13-group-scatter.html

Adds examples demonstrating new grouped scatter attributes

Add grouped scatter examples (next Plotly.js release)

---

_includes/layouts/webinar_plug.html

It's announced now so good to auto-deploy.

Change sidebar ad to Feb 2023 webinar

---

_includes/layouts/side-bar.html
_includes/posts/mainlang_documentation_eg.html

To close https://github.com/plotly/graphing-library-docs/issues/221

Remove Chart Studio from main page

---

_posts/plotly_js/fundamentals/axes/2023-03-15-axes-label-aliases.html
_posts/plotly_js/fundamentals/labels/2023-03-17-automargin.html
_posts/plotly_js/fundamentals/shapes/2023-03-15-labels-on-shapes.html

@nicolaskruchten would there be an issue with updating https://github.com/plotly/graphing-library-docs/blob/master/_data/jsversion.json this
or does it need to wait until Plotly.py is on the same version?

Examples for latest Plotly JS release 2.19.1

---

_includes/layouts/webinar_plug.html

Only for merging tomorrow (don't think it's announced yet).

Update sidebar ad to May 2023 webinar

---

_posts/plotly_js/scientific/heatmap/2015-08-12-heatmap-with-unequal-block-sizes.html

To close https://github.com/plotly/graphing-library-docs/issues/157

Fix width typo

---

_includes/layouts/webinar_plug.html

Swap sidebar ad back to Careers

---

_includes/layouts/_footer-main.html
_includes/layouts/head.html
all_static/css/markprompt.css
all_static/javascripts/chatbot.js

- Adds close button
- Adds hover to show keyboard shortcut for close button

Update chatbot to have close button

---

_posts/python-v3/ipython-notebooks/2015-06-30-baltimore.html
_posts/python-v3/ipython-notebooks/baltimore.ipynb

Partially resolves https://github.com/plotly/techops-infra/issues/479
It looks like his twitter presence is gone too

Remove link to unowned site

---

_includes/layouts/webinar_plug.html

@HammadTheOne Can I get you to check this in Liam's absence?

Change sidebar ad to Aug 2024 webinar

---

_posts/plotly_js/basic/dot/2015-08-11-categorical-dot-plot.html
_posts/plotly_js/basic/line-plots/2015-08-07-labelling-with-annotations.html
_posts/plotly_js/fundamentals/axes/2015-04-09-axes-ticks.html
_posts/plotly_js/fundamentals/colorscales/2015-08-10-discretized-heatmap-colorscale.html
_posts/plotly_js/fundamentals/images/2016-06-21-logo.html
_posts/plotly_js/fundamentals/shapes/2015-08-10-venn-diagram-with-circle-shapes.html

Replace removed `autotick` 
https://github.com/plotly/plotly.js/pull/7236/files

Replace removed autotick

---

_posts/csharp/indexes/2021-08-04-statistic-index.html
_posts/fsharp/indexes/2021-08-04-statistic-index.html
_posts/ggplot2/indexes/2021-08-04-statistic-index.html
_posts/julia/indexes/2021-08-04-statistic-index.html
_posts/matlab/indexes/2021-08-04-statistic-index.html
_posts/nodejs/histogram/2015-04-09-overlaid-histogram.html
_posts/plotly_js/README.md
_posts/plotly_js/basic/bubble/2015-08-10-size-scaling-bubblechart.html
_posts/plotly_js/controls/callbacks-buttons/2018-10-16-style-buttons.html
_posts/plotly_js/fundamentals/axes/2019-11-04-title_standoff.html
_posts/plotly_js/fundamentals/uirevision/2019-01-04-uirevision-reset.html
_posts/python-v3/statistical/2017-02-24-python-statistic-index.html
_posts/python-v3/statistics/frequency-counts/2015-06-30-python-Frequency-Counts.html
_posts/python-v3/statistics/frequency-counts/python-Frequency-Counts.ipynb
_posts/python/2019-07-03-statistic-index.html
_posts/r/README.md

This pull request just fixes some typos.

Fix some typos
